### ISSUE TITLE
libshout hangs

### ISSUE THREAD

**Issue by zygmund2000** [xiph/Icecast-libshout#14]
Hi,

I updated libshout to latest version 2.4.2 but after few days I downgraded back to 2.4.1 because it causes Ezstream to hangs few times a day. Maybe it is some compatibility problem.

**Comment by ghost** [comment]
hey, 

I downgrade also to 2.4.1. I have the impossibility to connect to stream with mixxx.

**Comment by zeronoises** [comment]
Adding my two cents worth - am also unable to connect via Mixxx since the update....

**Comment by ZanokRupert** [comment]
I have the same connection problem with Mixxx, hence I opened a issue on it. https://github.com/xiph/Icecast-libshout/issues/15

**Comment by dm8tbr** [comment]
Issue migrated to the actual project issue tracker:
https://gitlab.xiph.org/xiph/icecast-libshout/issues/2308
