### ISSUE TITLE
libshout-1:2.4.2-1 breaks live broadcasting Mixxx 2.2.1

### ISSUE THREAD

**Issue by ZanokRupert** [xiph/Icecast-libshout#15]
Hey, libshout version 1:2.4.2-1 seems to break the Mixxx broadcasting. I can't connect to the server at all.

When I downgrade to libshout-1:2.4.1-4 the broadcast works again.

I'm using Manjaro stable, this uses the 1:2.4.2-1 version.

I'm not sure if this is a problem on the Mixxx side, or on the libshout side. Hence I posted this bug also on the Mixxx Launchpad. https://bugs.launchpad.net/mixxx/+bug/1833225

UPDATE: I also tested version 2.4.3 from git. This version is also broken. https://aur.archlinux.org/packages/libshout-git/

**Comment by dm8tbr** [comment]
Dupe
