### ISSUE TITLE
provide tarballs for users

### ISSUE THREAD

**Issue by vtorri** [xiph/Icecast-libshout#16]
Hello

currently the tarball is a copy of the git repo. Would it be possible that a tarball could be released with 'make dist', or better (for the devs) with 'make distcheck' ? If so, a tarball compressed with xz would also provide a smaller  tarball.

thank you

**Comment by dm8tbr** [comment]
official release tarballs can be obtained here: https://ftp.osuosl.org/pub/xiph/releases/libshout/
