### ISSUE TITLE
OGG-FLAC support

### ISSUE THREAD

**Issue by ghost** [xiph/Icecast-libshout#18]
Are there plans to include OGG-FLAC support for this library?

I have a work-in-progress fork in https://github.com/ziplantil/Icecast-libshout ([compare](https://github.com/xiph/Icecast-libshout/compare/master...ziplantil:flac)) (under branch `flac`), but there are a couple of issues with it, which is why I chose to not do a PR just yet:
* it modifies the m4 files, which are submoduled on this repo. The only change needed after cloning is moving flac.m4 under the m4 folder.
* FLAC manages to encode long periods of silence into basically nothing, which seems to cause Icecast to raise a source timeout and cause a socket error (this might also be a programming error in the custom broadcasting program, though)
* I'm not sure if the code breaks any guidelines that have been set out for this project specifically.

**Comment by rillian** [comment]
Re the source timeout, Opus had a similar problem. For streaming, you might need to remux the file, calling `ogg_page_flush` if packets covering more than a certain amount of time (one second, say) have accumulated without hitting libogg's built-in size-based flush threshhold of 4 kB.

`opusenc` [does this at encode time](https://github.com/xiph/libopusenc/blob/b03c6c73cc30/src/ogg_packer.c#L305-L307), and you could make `flac` do that and/or do it on-the-fly in libshout. 

Depending on what icecast's timeout is, it's possible you could still have problems at low sample rates. The maximum block size of 64k samples is 8 seconds at 8 kHz. At normal sample rates and block sizes, it should be fine. Addressing that would require re-encoding the blocks, not just re-muxing at the Ogg layer.

**Comment by ghost** [comment]
I see. I don't think libshout's codec_opus does any page flushing, and therefore the consistent practice is probably not to do it with codec_flac either, leaving the job to the encoder. I'll try to use the weekend to check the code quality and hopefully start a PR once I've managed to get the code to a state where it could be merged.

**Comment by ghost** [comment]
Closing this now that the PR has been made
