### ISSUE TITLE
shout_set_metadata() for SHOUTcast

### ISSUE THREAD

**Issue by kawauso** [xiph/Icecast-libshout#3]
I've noticed that in shout_set_metadata(), the value of self->tls_mode remains SHOUT_TLS_AUTO even after connected to SHOUTcast server and always causes unsuccessful return. To (flat) icecast server, it is turned SHOUT_TLS_DISABLED and works fine.
FYI. Cheers.

**Comment by dm8tbr** [comment]
I've been informed, that we're tracking this already as https://trac.xiph.org/ticket/2244

So I'll be closing this issue as we track there.
