### ISSUE TITLE
libshout with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by tlschenkjr** [xiph/Icecast-libshout#7]
libshout contains calls to deprecated functions in openssl 1.1.0 and fails to build correctly.  Any chance of that getting updated?

**Comment by mfb** [comment]
I just noticed this as well :/

**Comment by tlschenkjr** [comment]
Unfortunately, as libshout seems to be stagnant, the solution in my case was to downgrade OpenSSL to 1.0.x.

**Comment by mfb** [comment]
I just stumbled on https://gitlab.xiph.org/xiph/icecast-libshout should issues be filed here or there?

**Comment by mfb** [comment]
I opened https://gitlab.xiph.org/xiph/icecast-libshout/issues/2299 in case that is the proper place

**Comment by fergalmoran** [comment]
The fix seems to be deleting the call to SSLeay_add_all_algorithms on line 66 in  src/tls.c
This is no longer needed as OpenSSL 1.1.0 as this is done automatically.

I can't fork the gitlab repo, otherwise I'd send in a pull request.

**Comment by dm8tbr** [comment]
This has been addressed in https://gitlab.xiph.org/xiph/icecast-libshout/issues/2299
