### ISSUE TITLE
Built for windows

### ISSUE THREAD

**Issue by hamswaldenkv** [xiph/Icecast-libshout#9]
Hello everyone
I'm windows user, how can i compile libshout for windows in order to stream with my application?
Thanks Advance

**Comment by hhrhhr** [comment]
0. the minimum required: _mingw-w64_ from Debian, Ubuntu or [Debian GNU/Linux for WSL](https://blogs.msdn.microsoft.com/commandline/2018/03/06/debian-gnulinux-for-wsl-now-available-in-the-windows-store/), and _libogg-dev, libvorbis-dev_ (builded with mingw)
1. patch src/Makefile.am:
````
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -22,7 +22,7 @@ endif
 SUBDIRS = common/avl common/net common/timing common/httpp $(MAYBE_THREAD)

 lib_LTLIBRARIES = libshout.la
-libshout_la_LDFLAGS = -version-info 5:0:2
+libshout_la_LDFLAGS = -version-info 5:0:2 -no-undefined

 EXTRA_DIST = codec_theora.c codec_speex.c tls.c
 noinst_HEADERS = format_ogg.h shout_private.h util.h
````
2. assume that the header files and libraries are in the _/mingw/(include|lib)_ directory.
(for x64 change build & host to _x86_64-w64-mingw32_)
````
> ./autogen.sh
> mkdir build && cd build
> ../configure --build=i686-w64-mingw32 --host=i686-w64-mingw32 --prefix=/mingw --disable-maintainer-mode
> make
> make install-strip
````

3. output files:
   - _/mingw/bin/libshout-3.dll_
   - _/mingw/include/shout/shout.h_
   - _/mingw/lib/libshout.a_
   - ...

**Comment by iesrbt** [comment]
Hi,
can someone provide, or link to, an already built libshout.dll for windows (10) please?
Thanks.

**Comment by hhrhhr** [comment]
@iesrbt , https://mega.nz/#!atgXmKgA!Ry3_2VX5M6JR7WMyvzYx3-KJIC9oj_VKIFoyDdcelig

**Comment by iesrbt** [comment]
@hhrhhr super cool! thanks a lot.

**Comment by yamgemy** [comment]
sorry noob question...where should i put these folders (bin, include lib, share) and what to do with them? i'm on windows 7

**Comment by tieb62** [comment]
> sorry noob question...where should i put these folders (bin, include lib, share) and what to do with them? i'm on windows 7

Where do I put the DLL ?

**Comment by el07694** [comment]
When i am trying to install python-shout in windows 10, one file is missing: shout.lib
Can you provide me please?

**Comment by el07694** [comment]
The libshout module works great for windows in msys2 platform.
Details: https://packages.msys2.org/package/mingw-w64-x86_64-libshout
If someone has tried to do it, with no success, just follow the instructions in the link: https://stackoverflow.com/questions/67127591/install-python-shout-module-in-windows-10-python-version-3-9

**Comment by el07694** [comment]
There is one more alternative: libshout + pthread + libogg + libvordis + Microsoft Visual Studio (2017+).
In github page of project mixxx there are instructions to build libshout with this logic

**Comment by el07694** [comment]
I have a .whl:

https://github.com/el07694/python-shout-for-windows-11-and-python-3.11.4

run as admin the cmd

**Comment by MrKhay** [comment]
Hi,
can someone provide, or link to, an already built libshout.so for android please?
Thanks.
